const String queryJoin = """
query joinContent{
  webJoin{
    data{
      attributes{
        project{
          data{
            attributes{
              Icon{
                data{
                  attributes{
                    url
                  }
                }
              }
              Name
              Description
              RelatedODS (sort: "name:asc", pagination: { limit: 20 }){
                data{
                  attributes{
                    name
                    url
                  }
                }
              }
            }
          }
        }
        Convenio{
          Title
          Description
          convenio{
            data{
              attributes{
                Logos{
                  data{
                    attributes{
                      url
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
  """;
