const String queryAboutUs = """
 query AboutUsContent {
  webAboutUs{
    data{
      attributes{
        Introduction{
          Icon{
              data{
                attributes{
                  url
                  caption
                }
              }
            }
          Title
          Description
          Picture{
            data{
              attributes{
                url
              }
            }
          }
        }
        Goal{
          Icon{
            data{
              attributes{
                url
              }
            }
          }
          Title
          Description
        }
        Values{
          Title
          Values{
            Icon{
              data{
                attributes{
                  url
                }
              }
            }
            Title
            Description
          }
        }
        Convenio{
          Title
          Description
          convenio{
          data{
            attributes{
              Logos{
                data{
                  attributes{
                    url
                  }
                }
              }
            }
          }
        }
        }
      }
    }
  }
}
  """;
