const String queryModelo = """
       query ModeloDeAtencionContent {
      webModelo{
        data{
          attributes{
            Introduccion{
              Icon{
                data{
                  attributes{
                    url
                  }
                }
              }
              Title
              Description
              Picture{
                data{
                  attributes{
                    url
                  }
                }
              }
            }
            Ambitos{
              Title
              Ambitos{
                data{
                  attributes{
                    Name
                    Icon{
                      data{
                        attributes{
                          url
                        }
                      }
                    }
                    Description
                    RelatedODS{
                      data{
                        attributes{
                          url
                        }
                      }
                    }
                  }
                }
              }
            }
            Voluntarios{
              Title
              Voluntarios(sort: "Title:asc", pagination: { limit: 50 }){
                Title
                Description
                Picture{
                  data{
                    attributes{
                      url
                    }
                  }
                }
              }
            }
          }
        }
      }
      }
""";
